import type { NormalisedAnchor } from "./anchors";
import type { Validation } from "./reconstruct";

const iso = (ms: number): string => new Date(ms).toISOString().replace(".000Z", "Z");
const fixed = (value: number | undefined, digits: number): string => (value === undefined ? "n/a" : value.toFixed(digits));

function table(header: readonly string[], rows: readonly (readonly (string | number)[])[]): string {
  const lines = [`| ${header.join(" | ")} |`, `|${header.map(() => "---").join("|")}|`];
  for (const row of rows) lines.push(`| ${row.join(" | ")} |`);
  return lines.join("\n");
}

const INTRO = `# Apollo 11 Reconstruction — Validation Report

> Generated by \`npm run apollo11:reconstruct\` from \`tools/apollo11\`. Do not edit by hand; edit the tool or its config and re-run.

This is a **reconstruction** of the Apollo 11 flight path from sparse NASA postflight anchor states (Mission Report MSC-00171 / SP-238). It is not the exact flight path and makes no accuracy claim between anchors beyond the measurements below.

## Method by segment

| Segment kind | Method |
|---|---|
| Parking orbit (Earth orbit insertion → TLI ignition) | No NASA anchor exists before TLI ignition (A-01). A-01 integrated **backward** in time with the coast dynamics below. Unanchored at the start; drag is ignored. |
| Coast between anchors (including Earth ↔ Moon) | Numerical integration (RK4, fixed step) in Earth-centred EQJ with Earth point mass + J2, and the Moon and Sun as third bodies from the Astraeus adapter. Integrated forward from the earlier anchor and backward from the later one, then smoothed (see Joins). |
| Ordinary burn (ignition → cutoff anchors) | Numerical integration from the ignition state with Earth (J2), Moon and Sun gravity plus a constant EQJ acceleration solved to reach the cutoff velocity. The cutoff position residual is reported; the next coast starts from the modelled cutoff state. This is not guidance. |
| Powered descent (PDI → touchdown) | Two-anchor cubic Hermite in the Moon-fixed frame. The 2022 NASA descent reconstruction was not used (docs/APOLLO11_SOURCES.md section 3). |
| Surface stay | The touchdown site held fixed in the Moon-fixed frame (IAU lunar rotation model). |
| Powered ascent (lift-off → ascent insertion) | Two-anchor cubic Hermite in the Moon-fixed frame, from the touchdown site at the lift-off event time. |

Moon-relative states are normalised offline to Earth-centred EQJ with the Astraeus Moon state at the same instant. Earth-fixed anchors use the Fischer 1960 ellipsoid and Orb's ECEF→EQJ transform; Moon-fixed anchors use the IAU WGCCRE lunar rotation on a 1,738.09 km sphere for position; Moon-referenced flight-path angle and heading are taken in a local basis whose north points to the EQJ (J2000) pole, adopted because the lunar-orbit anchors are only consistent that way (owner decision 2026-10-06; the source does not define it). Conventions are in \`docs/APOLLO11_SOURCES.md\` section 4.

**Joins (smoothing).** Propagated forward from its start state alone, a coast still misses its next anchor; that **raw miss** is measured and published below. After a burn, this forward state is the modelled cutoff state; otherwise it is the converted start anchor. The coast is blended to a backward propagation from the next anchor with a smoothstep weight (0 with zero slope at the start, 1 with zero slope at the end), interpolating radius linearly and direction along the great circle about the Moon when both anchors are Moon-referenced, otherwise about Earth. Non-cutoff anchors are met in position and velocity, and \`discontinuities\` is empty. The largest difference between the smoothed and raw forward path is published per coast as the correction. Large corrections are a presentation repair over doubtful data, not physics.

**Sample interval.** Per segment, the largest interval from a fixed ladder whose cubic Hermite error at held-out midpoints is at most 0.25 km. The measured maximum is reported below.
`;

/** Coasts whose smoothing correction is large enough to matter, named so the repair is never invisible. */
function largeCorrections(validation: Validation): string {
  const { km, ms } = validation.smoothingReportThreshold;
  const rows = validation.segments.filter(
    (s) => (s.maxCorrectionKm ?? 0) > km || (s.maxCorrectionMs ?? 0) > ms,
  );
  if (rows.length === 0) return `- No coast needed a smoothing correction above ${km} km or ${ms} m/s.\n`;
  const list = rows
    .map((s) => `${s.id} (${s.vehicle}, ${fixed(s.maxCorrectionKm, 0)} km / ${fixed(s.maxCorrectionMs, 0)} m/s)`)
    .join("; ");
  const tliBurn = validation.segments.find((s) => s.id === "A-01>A-02");
  const postTliCoast = validation.segments.find((s) => s.id === "A-02>A-03");
  const tliNote = tliBurn?.cutoffPositionResidualKm === undefined || postTliCoast === undefined
    ? ""
    : ` The ${Math.round((postTliCoast.endUtcMs - postTliCoast.startUtcMs) / 1000)}-second A-02>A-03 coast starts from the modelled A-01>A-02 cutoff, whose ${fixed(tliBurn.cutoffPositionResidualKm, 1)} km position residual is listed above.`;
  return `- Coasts smoothed by more than ${km} km or ${ms} m/s: ${list}. Their anchors disagree with each other under these dynamics.${tliNote} Elsewhere, likely causes include printed headings that do not fit the orbit plane, lunar gravity anomalies omitted by the point-mass Moon, and print rounding. Treat the path there as illustrative.\n`;
}

export function renderReport(validation: Validation, anchors: ReadonlyMap<string, NormalisedAnchor>): string {
  const suspect = new Set(validation.suspectAnchors.ids);
  const parts: string[] = [INTRO];

  parts.push(
    "## Source anchors and start-state residuals\n\n" +
      "Residual = generated trajectory evaluated at the anchor time versus the converted anchor. Non-cutoff anchors target ≤ 1e-6 km; burn cutoff anchors are allowed to differ and their modelled residuals are published. " +
      "The last two columns are the effect of half a unit in each printed digit and of ±0.05 s in time, a property of the table, not of the tool.\n\n" +
      table(
        ["Anchor", "Vehicle", "GET", "Event", "Residual km", "Residual m/s", "Print rounding km", "Print rounding m/s", "Flag"],
        validation.anchorResiduals.map((row) => {
          const anchor = anchors.get(row.anchorId)!;
          return [
            row.anchorId,
            row.vehicle,
            anchor.getPrinted,
            anchor.event,
            fixed(row.positionKm, 6),
            fixed(row.velocityMs, 6),
            fixed(anchor.printRoundingUncertainty.positionKm, 2),
            fixed(anchor.printRoundingUncertainty.velocityMs, 2),
            anchors.get(row.anchorId)!.inferredOverride !== undefined ? "inferred override" : suspect.has(row.anchorId) ? "suspect" : "",
          ];
        }),
      ),
  );

  parts.push(
    "## Segments, cutoff residuals, raw misses, smoothing corrections and interpolation error\n\n" +
      "Cutoff residual = the physical burn's modelled cutoff state versus the printed cutoff anchor. Raw miss = the coast propagated from its start state alone, at the next NASA anchor. **No pass/fail threshold is applied to those residuals.** " +
      "Correction = the largest position and velocity difference between the smoothed path and that raw propagation. Two-anchor descent and ascent segments reach their end anchor by construction (—).\n\n" +
      table(
        ["Vehicle", "Segment", "Method", "Start UTC", "End UTC", "Interval s", "Samples", "Cutoff residual km", "Cutoff residual m/s", "Peak speed km/s", "Speed reference", "Raw miss km", "Raw miss m/s", "Correction km", "Correction m/s", "Interp. max km", "Interp. max m/s"],
        validation.segments.map((s) => [
          s.vehicle,
          s.id,
          s.method,
          iso(s.startUtcMs),
          iso(s.endUtcMs),
          s.intervalS,
          s.sampleCount,
          s.cutoffPositionResidualKm !== undefined ? fixed(s.cutoffPositionResidualKm, 3) : "—",
          s.cutoffVelocityResidualMs !== undefined ? fixed(s.cutoffVelocityResidualMs, 6) : "—",
          s.peakSpeedKmS !== undefined ? fixed(s.peakSpeedKmS, 3) : "—",
          s.speedReferenceBody ?? "—",
          s.rawMissKm !== undefined ? fixed(s.rawMissKm, 1) : "—",
          s.rawMissMs !== undefined ? fixed(s.rawMissMs, 1) : "—",
          s.maxCorrectionKm !== undefined ? fixed(s.maxCorrectionKm, 1) : "—",
          s.maxCorrectionMs !== undefined ? fixed(s.maxCorrectionMs, 1) : "—",
          fixed(s.interpolationMaxKm, 4),
          fixed(s.interpolationMaxMs, 4),
        ]),
      ),
  );

  parts.push(
    "## Runtime one-second speed scan\n\n" +
      "Each vehicle's runtime `SampledTrajectory` is probed in one-second intervals. The travelled distance is compared with the maximum Earth-centred speed at the interval start, midpoint and end; a violation is more than 0.001 km beyond that local speed.\n\n" +
      table(
        ["Vehicle", "Seconds checked", "Violations", "Largest excess km", "Worst interval start UTC"],
        Object.entries(validation.oneSecondSpeedScan).map(([vehicle, scan]) => [
          vehicle,
          scan.checkedSeconds,
          scan.violationCount,
          fixed(scan.maxExcessKm, 6),
          scan.worst === undefined ? "—" : iso(scan.worst.startUtcMs),
        ]),
      ) +
      "\n\nThe per-burn peak speeds above are measured through the runtime `SampledTrajectory` at 100 ms intervals, including each cutoff. Moon-referenced burns report speed relative to the Moon; Earth-referenced burns report Earth-centred speed.\n",
  );

  const overrides = [...anchors.values()].filter((a) => a.inferredOverride !== undefined);
  if (overrides.length > 0) {
    parts.push(
      "## Inferred overrides\n\n" +
        "Manually approved exceptions. The raw source value is unchanged; the reconstruction uses the value below. This is not a source correction.\n\n" +
        overrides
          .map((a) => {
            const o = a.inferredOverride!;
            return `### ${a.id} — ${o.field}\n\n- Printed source value: ${o.printedValue}\n- Reconstruction value: ${o.reconstructionValue}\n- Status: \`${o.status}\`; confidence: ${o.confidence}\n- ${o.decision}\n- Evidence:\n${o.evidence.map((e) => `  - ${e}`).join("\n")}`;
          })
          .join("\n\n"),
    );
  }

  const consistency = validation.consistency;
  parts.push(
    `## Anchor consistency (Earth anchors versus ${consistency.reference})\n\n` +
      "Each later Earth-reference anchor up to A-09 is compared with the state two-body-propagated from " +
      `${consistency.reference}. Large differences mark printed values that disagree with their neighbours. The raw values are kept unchanged and flagged; they are not corrected here.\n\n` +
      table(
        ["Anchor", "Position diff km", "Alt printed / predicted nmi", "Speed printed / predicted ft/s", "FPA printed / predicted °", "Heading printed / predicted °", "Lon printed / predicted °", "Flag"],
        consistency.rows.map((row) => [
          row.anchorId,
          fixed(row.positionDifferenceKm, 0),
          `${row.printed.altitudeNmi} / ${row.predicted.altitudeNmi}`,
          `${row.printed.speedFtS} / ${row.predicted.speedFtS}`,
          `${row.printed.flightPathAngleDeg} / ${row.predicted.flightPathAngleDeg}`,
          `${row.printed.headingDeg} / ${row.predicted.headingDeg}`,
          `${row.printed.longitudeDeg} / ${row.predicted.longitudeDeg}`,
          row.overridden ? "inferred override used" : row.suspect ? "suspect" : "",
        ]),
      ) +
      `\n\n${validation.suspectAnchors.note}`,
  );

  parts.push(
    "## Independent cross-check: published lunar orbits\n\n" +
      "Apsis altitudes (above the 1,738.09 km reference sphere) from the converted post-burn anchor, versus the orbit values in the Mission Report as recorded in docs/APOLLO11_SOURCES.md section 5. " +
      "The osculating two-body values are expected to differ by a few n mi because of lunar gravity anomalies.\n\n" +
      table(
        ["Anchor", "Published apolune / perilune n mi", "Computed apolune / perilune n mi", "Source"],
        validation.orbitCrossChecks.map((row) => [
          row.anchorId,
          `${row.publishedApoluneNmi} / ${row.publishedPeriluneNmi}`,
          `${row.computedApoluneNmi} / ${row.computedPeriluneNmi}`,
          row.source,
        ]),
      ),
  );

  const q = validation.qualitative;
  parts.push(
    "## Qualitative checks (brief section 20)\n\n" +
      `- **Departure side.** Angle between the Earth-centred TLI position (A-03) and the Moon's direction at lunar orbit insertion: **${q.departure.angleBetweenTliPositionAndMoonAtLoiDeg}°** (departure on the side of Earth opposite the Moon's arrival position is ≈ 150–180°).\n` +
      (q.arrival === undefined
        ? ""
        : `- **Moon at arrival.** The path enters the Moon's 66,200 km sphere of influence at ${q.arrival.sphereOfInfluenceUtcMs === undefined ? "n/a" : iso(q.arrival.sphereOfInfluenceUtcMs)}. One second before the LOI anchor it is ${q.arrival.propagatedSelenocentricRadiusKm} km from the time-matched Moon (the anchor is at ${q.arrival.anchorSelenocentricRadiusKm} km).\n`) +
      `- **Lunar orbit surrounds the current Moon.** Altitude above the Moon at the same instant, A-12 to A-32 (Columbia): ${q.lunarOrbit.columbia.minAltitudeKm} to ${q.lunarOrbit.columbia.maxAltitudeKm} km over ${q.lunarOrbit.columbia.probes} probes; closest approach to the Moon's position at orbit insertion would be ${q.lunarOrbit.columbia.minDistanceToMoonPositionAtOrbitInsertionKm} km if the Moon were stale. Eagle, whole trajectory: ${q.lunarOrbit.eagle.minAltitudeKm} to ${q.lunarOrbit.eagle.maxAltitudeKm} km. Negative altitudes would be paths below the reference sphere.\n` +
      `- **Return meets Earth.** On the final (smoothed) coast, the path is at ${q.entryInterface.propagatedAltitudeAtAnchorTimeKm} km altitude at the entry-interface anchor time, and crosses ${q.entryInterface.entryAltitudeKm} km (400,000 ft) ${q.entryInterface.crossingMinusAnchorSeconds} s after it (beyond the anchor the path follows the backward propagation from it).\n\n` +
      "### Landing site versus the runtime Moon orientation\n\n" +
      "The IAU-placed site compared with the same selenographic latitude/longitude under the runtime tidal-lock Moon orientation. The offset is larger than the 1°–2° anticipated in docs/APOLLO11_SOURCES.md because the runtime orientation has no libration. The Moon mesh is deliberately not adjusted to hide this.\n\n" +
      table(
        ["Time UTC", "Offset km", "Offset °"],
        validation.landingSiteOffset.map((o) => [iso(o.timeUtcMs), o.offsetKm, o.offsetDeg]),
      ) +
      "\n\n### Surface clearance of the two-anchor arcs\n\n" +
      "Lowest altitude above the 1,738.09 km reference sphere, probed every second.\n\n" +
      table(
        ["Segment", "Minimum altitude km"],
        validation.surfaceClearance.map((c) => [c.segmentId, c.minAltitudeKm]),
      ),
  );

  parts.push(
    "## Known gaps and unsupported claims\n\n" +
      "- No accuracy claim is made between anchors. The raw misses above show how far the propagated path is from the next anchor before smoothing; the smoothed path hides that step on screen but does not make the path more accurate.\n" +
      largeCorrections(validation) +
      "- Moon-referenced flight-path angle and heading are read against Earth-equatorial (EQJ) north. Table 7-II does not say which north applies at the Moon; the reading is adopted because, under it, the lunar-orbit anchors share one orbit plane and A-10>A-11 and A-32>A-33 nearly close (`docs/ASTRAEUS_SPIKE_02.md` section 7.2). Under lunar north they scatter by up to about 17°.\n" +
      "- A-33/A-34 speeds are printed as 4 375.0 / 4 374.0 ft/s with an illegible hundreds digit; owner-approved inferred overrides use 4 075.0 / 4 074.0 ft/s (see Inferred overrides). This is not documentary-confirmed from the primary scan.\n" +
      "- A-05's flight-path angle is printed as 44.94° but disagrees with its neighbours; the reconstruction uses an owner-approved **inferred override** of 49.94° (probable source typo, high confidence, not documentary-confirmed). The raw value is unchanged and the override is recorded in `data/apollo11/normalised/anchors.json`. Overrides are manual, owner-approved exceptions (A-05, A-33, A-34), not a general data-repair mechanism.\n" +
      "- The parking orbit is propagated backward from the TLI-ignition anchor with no NASA anchor of its own.\n" +
      "- Ordinary burns use constant inertial acceleration with Earth J2, Moon and Sun gravity. Their cutoff velocities are fitted and residuals are listed above; the model does not reproduce guidance, mass flow or variable thrust. Powered descent and ascent remain two-anchor interpolations and do not represent guidance.\n" +
      "- Moon-fixed anchors use the IAU mean-Earth/polar-axis frame; the Apollo-era selenographic frame may differ by up to about a kilometre.\n" +
      "- UTC is used for time; UT1−UTC and TT−UTC (taken as 39.7 s for the lunar rotation) are approximations well under the 1 km tolerance.\n" +
      "- Launch, ascent to orbit, parachute descent and splashdown exist only as events.\n",
  );
  return `${parts.join("\n\n")}\n`;
}
